# Generated by Django 4.2.4 on 2023-08-30 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "phonebook_app",
            "0002_contact_address_contact_categories_contact_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Kategori", "verbose_name_plural": "Kategoriler"},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "İletişim", "verbose_name_plural": "İletişimler"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Lokasyon", "verbose_name_plural": "Lokasyonlar"},
        ),
    ]
