# Generated by Django 4.2.4 on 2023-08-31 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0003_alter_category_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Person",
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Kişi", "verbose_name_plural": "Kişiler"},
        ),
    ]
