# Generated by Django 4.2.4 on 2023-08-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0004_rename_contact_person_alter_person_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="categories",
            field=models.ManyToManyField(
                related_name="persons", to="phonebook_app.category"
            ),
        ),
    ]
