# Generated by Django 4.2.4 on 2023-08-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0005_alter_person_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="address",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
