# Generated by Django 4.2.4 on 2023-08-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0006_alter_person_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
