# Generated by Django 4.2.4 on 2023-08-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0007_alter_person_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["id"],
                "verbose_name": "Kişi",
                "verbose_name_plural": "Kişiler",
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="categories",
            field=models.ManyToManyField(
                related_name="phonebook_app", to="phonebook_app.category"
            ),
        ),
    ]
