# Generated by Django 4.2.4 on 2023-08-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0008_alter_person_options_alter_person_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="categories",
            field=models.ManyToManyField(to="phonebook_app.category"),
        ),
    ]
