# Generated by Django 4.2.4 on 2023-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0010_uploadimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/persons"),
        ),
    ]
