# Generated by Django 4.2.4 on 2023-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0011_alter_person_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
