# Generated by Django 4.2.4 on 2023-09-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0013_alter_person_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="name",
            new_name="neighbourhood",
        ),
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
