# Generated by Django 4.2.4 on 2023-09-04 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0015_person_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="location",
        ),
    ]
