# Generated by Django 4.2.3 on 2023-09-26 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook_app", "0017_person_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadImage",
        ),
        migrations.RemoveField(
            model_name="person",
            name="image",
        ),
    ]
